name: Setup Windows RDP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Create RDP User
      run: |
        $username = "rdpuser"
        $password = ConvertTo-SecureString "YourPasswordHere" -AsPlainText -Force
        New-LocalUser -Name $username -Password $password -FullName "RDP User" -Description "User for Remote Desktop Access"
        Add-LocalGroupMember -Group "Administrators" -Member $username

    - name: Start ngrok tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    - name: Output connection info
      run: |
        echo "RDP is set up and running."
        echo "You can connect using the following command:"
        echo "RDP Client Address: $(curl --silent http://localhost:4040/api/tunnels | ConvertFrom-Json).tunnels[0].public_url"
